# FA coverage build helpers (green branch — tests/support gate)
option(FA_ENABLE_COVERAGE "Enable gcov/lcov flags on feedback_analyzer_tests" OFF)

function(fa_apply_coverage target_name)
    if(NOT FA_ENABLE_COVERAGE)
        return()
    endif()
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        message(WARNING "FA_ENABLE_COVERAGE: only GNU gcov is supported; flags skipped.")
        return()
    endif()
    target_compile_options(${target_name} PRIVATE --coverage -O0 -g)
    target_link_options(${target_name} PRIVATE --coverage)
endfunction()
